export { default as Appointment } from './appointment.entity';
export { default as Customer } from './customer.entity';
export { default as Treatment } from './treatment.entity';
export { default as User } from './user.entity';
export { default as Role } from './role.entity';
export { default as GoogleToken } from './google-token.entity';
export { default as Schedule } from './schedule.entity';
export { default as Product } from './product.entity';
export { default as UserProfile } from './user.profile.entity';
